name: CI
on:
  workflow_dispatch:

jobs:
  test:
    outputs:
      artifact_url: ${{ steps.upload-artifact.outputs.artifact-url }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
    - run: npm install
    - run: npm test
    - uses: actions/upload-artifact@v4
      id: upload-artifact
      with:
        name: 'test'
        path: ./index.js
        overwrite: true

  download:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - run: |
          artifact_id=$(basename ${{ needs.test.outputs.artifact_url }}) &&
          echo "Artifact_id: $artifact_id" &&
          curl -L -o test.zip \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          "https://api.github.com/repos/${{ github.repository }}/actions/artifacts/$artifact_id" &&
          ls -la
          file test.zip
          cat test.zip




