name: CI
on:
  workflow_dispatch:

jobs:
  test:
    outputs:
      artifact_url: ${{ steps.upload-artifact.outputs.artifact-url }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        server: ["${{ vars.STAGE_SERVER }}"]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
    - run: npm install
    - run: npm test
    - run: echo "This is github context ${{ github }}"
    - uses: actions/upload-artifact@v4
      id: upload-artifact
      with:
        name: 'test'
        path: ./index.js
        overwrite: true

  download:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - run: |
          artifact_id=$(basename ${{ needs.test.outputs.artifact_url }}) &&
          download_url="https://api.github.com/repos/${{ github.repository }}/actions/artifacts/$artifact_id/zip"
          echo "Artifact_id: $artifact_id" &&
          echo "Download url: $download_url" &&
          curl -L -o test.zip -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" $download_url &&
          ls -la
          file test.zip
          cat test.zip




