name: CI
on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
    - run: npm install
    - run: npm test
    - uses: actions/upload-artifact@v4
      with:
        name: 'test'
        path: ./index.js
        overwrite: true
